### ISSUE TITLE
Improvement Proposal: Enhance Documentation and Implement Realistic Design

### ISSUE THREAD

**Issue by sahil-tgs** [abhinavxanand/Void#1]
**Issue Description:**

The current state of the project's documentation is inadequate, making it difficult for contributors to understand the codebase. Additionally, the existing code implements a simplistic approach that may not reflect the complexity and realism required for our project's goals.

**Proposed Solution:**

Improve project documentation with clear explanations and code comments.
Implement a more realistic and complex design aligned with project objectives, considering factors such as:
Preassigned seats

- Database implementation 
- Exceptional cases
- Gender-based allocation
- 'Berth' allocation instead of 'seat' allocation
- Handling multiple simultaneous entries with the same database

**Comment by abhinavxanand** [comment]
Points in the proposed solution will be looked upon in due process of repo changes.
